BEGIN;

CREATE TABLE courses (
    id INTEGER NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    "time" TEXT NOT NULL,
    room TEXT NOT NULL,
    professor TEXT NOT NULL,
    department TEXT NOT NULL,
    description TEXT,
    credits INTEGER NOT NULL,
    CONSTRAINT courses_pkey PRIMARY KEY (id)
);

CREATE TABLE deadlines (
    deadline_id INTEGER NOT NULL,
    deadline_title TEXT NOT NULL,
    deadline_date DATE NOT NULL,
    deadline_description TEXT,
    CONSTRAINT deadlines_pkey PRIMARY KEY (deadline_id)
);

CREATE TABLE dining (
    dining_id INTEGER NOT NULL,
    dining_name TEXT NOT NULL,
    opening_time TEXT NOT NULL,
    closing_time TEXT NOT NULL,
    dining_location TEXT NOT NULL,
    dining_status TEXT NOT NULL,
    CONSTRAINT dining_pkey PRIMARY KEY (dining_id)
);

CREATE TABLE events (
    event_id INTEGER NOT NULL,
    event_name TEXT NOT NULL,
    event_date DATE NOT NULL,
    event_time TEXT NOT NULL,
    event_location TEXT NOT NULL,
    event_description TEXT,
    event_category TEXT NOT NULL,
    CONSTRAINT events_pkey PRIMARY KEY (event_id)
);

CREATE TABLE professors (
    professor_id INTEGER NOT NULL,
    professor_name TEXT NOT NULL,
    professor_department TEXT NOT NULL,
    professor_email TEXT,
    office_location TEXT,
    professor_rating REAL,
    CONSTRAINT professors_pkey PRIMARY KEY (professor_id)
);

CREATE TABLE student_interests (
    interest_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    student_id INTEGER NOT NULL,
    interest TEXT NOT NULL,
    CONSTRAINT student_interests_pkey PRIMARY KEY (interest_id)
);

COMMIT;
